{% set version = "2022.1" %}

package:
  name: python-tzdata
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tzdata/tzdata-{{ version }}.tar.gz
  sha256: 8b536a8ec63dc0751342b3984193a3118f8fca2afe25752bb9b7fffd398552d3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - tzdata

about:
  home: https://github.com/python/tzdata
  license: Apache-2.0
  license_file: LICENSE
  summary: Provider of IANA time zone data

  description: |
    This is a Python package containing zic-compiled binaries for the IANA time zone database.
    It is intended to be a fallback for systems that do not have system time zone data installed (or don't have it installed in a standard location),
    as a part of PEP 615.

extra:
  recipe-maintainers:
    - ocefpaf
    - pganssle
    - mbargull
